config/routes.rb
PackPickup::Application.routes.draw do
  root to: 'sessions#new' 

  #create a named route called register automatically
  #CRUD is not applicable so resource is not an appropriate choice,
  #instead manually build routes 
  #get '/register', to: 'residents#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :residents do   
    resources :packages do 
      member do # will build 'POST /posts/id' part of route
        post :new
      end
    end
  end

  resources :apartments, only: [:index, :edit, :update] 
end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  has_many :residents

  validates_presence_of :rent, :description

  #validates :apartment_number, presence: true
  validates :apartment_number, presence: true, inclusion: {in: %w(1A 1B 1C 2A 2B 2C),
    message: "invalid"}
 
end
 

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :require_admin
  before_action :set_apartment, only: [:edit, :update]
  
  # GET '/'
  def index
    @apartments = Apartment.all
    render 'apartments/index' #happens by default and end of each method
  end


  # GET '/apartments/id/edit'
  def edit #url will be something like /apartment/3/edit, edit form will be rendered
    #@apartment = Apartment.find(params[:id]) #set_apartment does this
    #edit.html... rendered by default
  end

  # PATCH '/apartments/id'
  #the general pattern used in the action create that handles
  #submission of model-backed forms 
  def update # this is where the form displayed in 'edit' is submitted using verb "patch"
    if @apartment.update(apartment_params)
      flash[:notice] = "Apartment information updated"
      # send to show apartment_path (add _path to the prefix)
      redirect_to apartments_path(@apartment)
    else
      render :edit
    end
  end

  private

  def apartment_params
    #use strong parameters to expose the fields we're interested in
    #require top level key be apartment and allow changes to fields
    params.require(:apartment).permit(:apartment_number,
     :description, :rent, :date_available)
    #To permit all attributes 
    #params.require(:apartment).permit!
  end

  def set_apartment
    # ask ActiveRecord to find the Apartment object in the db using the id from params
    @apartment = Apartment.find(params[:id]) #looking at the model layer
    #@apartment = Apartment.find_by(slug: params[:id])
  end


end

app/views/apartments/_form.html.erb
<%= render 'shared/errors', obj: @apartment %>

<div class = 'well'>
  <%= form_for @apartment do |f| %>
    <div class = 'control-group'>
      <%= f.label :apartment_number %>
      <br/>
      <%= f.text_field :apartment_number%>
    </div>
    <div class = 'control-group'>
      <%= f.label :description %>
      <br/>
      <%= f.text_area :description%>
    </div>  
    <div class = 'control-group'>
      <%= f.label :rent %>
      <br/>
      <%= f.text_field :rent %>
    </div>
    <br/>  
    <%= f.submit(@apartment.new_record? ? 'Create Apartment' : 'Update Apartment', class:'btn btn-primary')%>
  <% end %>
</div>

app/views/apartments/edit.html.erb
<%= render 'form' %>

app/views/apartments/index.html.erb
<div class="container">
  <h2>Apartment Manager</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Edit Apartment</th>
        <th>Description</th>
        <th>Rent</th>
      </tr>
    </thead>
    <tbody>   
        <% @apartments.each do |a| %>
          <tr>
            <td> <%= link_to(a.apartment_number, edit_apartment_path(a)) %> </td>
            <td><%= a.description%></td>
            <td><%= a.rent.to_s(:currency)%></td>
          </tr>
        <% end %>   
    </tbody>
  </table>
</div>

app/views/apartments/new.html.erb
<%= render 'form' %>