config/routes.rb
PackPickup::Application.routes.draw do
  root to: 'sessions#new' 

  #create a named route called register automatically
  #CRUD is not applicable so resource is not an appropriate choice,
  #instead manually build routes 
  #get '/register', to: 'residents#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :residents do   
    resources :packages do 
      member do # will build 'POST /posts/id' part of route
        post :new
      end
    end
  end

  resources :apartments, only: [:index, :edit, :update] 
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<h2> Package Pick-up </h2>

<% if logged_in? %>
  <p class='pull-right'> 
    <%= link_to 'Logout', logout_path, class: 'btn btn-danger btn-large'%> 
  </p>
  <ul class="nav nav-tabs">
    <% if current_user.admin? %> 
      <div class="btn-group btn-group-justified">
          <%= link_to 'Apartments', apartments_path, class: 'btn btn-primary btn-large' %>      
          <%= link_to 'Residents', residents_path, class: 'btn btn-primary btn-large' %>   
          <%= link_to 'Add New Resident', new_resident_path, class: 'btn btn-primary btn-large' %>    
      </div> 
    <%else%> 
      <li class="active">
        <%= link_to('', class: 'btn btn-large dropdown-toggle', 'data-toggle' => 'dropdown') do %>
          <%= current_user.first_name %>
          <span class='caret'></span>
        <% end %>
        <ul class='dropdown-menu'>
          <% if params[:action]=="show"%>
            <li>
              <%= link_to edit_resident_path(current_user) do %>
                <i class='icon-pencil'></i>edit profile
              <% end %>
            </li>
          <%else%>
            <li>
              <%= link_to resident_path(current_user) do %>
                 <i class='icon-home'></i>
                  show packages
              <% end %>
            </li>
          <%end%>
        </ul>
      </li>
    <%end%>
  </ul> 
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Package Pick-Up </title>
    <meta name="description" content="Set/Access resident package delivery status">
    <meta name="author" content="Gigi Wolff">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>